spring.r2dbc.url=r2dbc:sqlserver://java-api-db.cwbgg4kmcxok.us-east-1.rds.amazonaws.com:1433/Banks?encrypt=true&trustServerCertificate=true

spring.r2dbc.username=sa
spring.r2dbc.password=Admin123

server.error.include-binding-errors=always
server.error.include-message=always

api.base-url=http://localhost:8080/api/v1