spring.r2dbc.url=r2dbc:sqlserver://127.0.0.1:1433/Banks
spring.r2dbc.username=sa
spring.r2dbc.password=Admin123
spring.r2dbc.properties.encrypt=false
spring.r2dbc.properties.trustServerCertificate=true
server.error.include-binding-errors=always
api.base-url=http://localhost:8080/api/v1/