name: Deploy artifact to AWS ECS

on:
  repository_dispatch:
    types: [deploy-artifact-event]


jobs:

  download-artifact-job:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      actions: read

    steps:

      ########################################################
      # 1- Retrieve parameters from payload
      ########################################################
      - name: Retrieve Payload
        run: |
          echo "Artifact: ${{ github.event.client_payload.artifact_name }}"
          echo "Checksum: ${{ github.event.client_payload.checksum }}"


      ########################################################
      # 2- Download JAR Artifact
      ########################################################
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: publishJarAsArtifact.yaml
          workflow_conclusion: success
          name: artifactjar
          path: /tmp/artifactjar


      - name: Display downloaded files
        run: |
          ls -R /tmp/artifactjar


      ########################################################
      # 3- Verify checksum
      ########################################################
      - name: Calculate checksum
        run: |
          echo "HASH=$(sha1sum /tmp/artifactjar/${{ github.event.client_payload.artifact_name }} | awk '{print $1}')" >> $GITHUB_ENV


      - name: Compare checksum
        run: |
          if [ "${{ env.HASH }}" == "${{ github.event.client_payload.checksum }}" ]; then
            echo "Checksum OK"
          else
            echo "Checksum ERROR"
            exit 1
          fi


      ########################################################
      # 4- Prepare Docker Context
      ########################################################
      - name: Checkout source
        uses: actions/checkout@v4


      - name: Prepare Docker Context
        run: |
          mkdir dockerBuildContext

          cp Arquitectura/Dockerfile dockerBuildContext/Dockerfile

          cp /tmp/artifactjar/${{ github.event.client_payload.artifact_name }} \
          dockerBuildContext/${{ github.event.client_payload.artifact_name }}


      - name: Upload Docker Context
        uses: actions/upload-artifact@v4
        with:
          name: dockerBuildContext
          path: dockerBuildContext/


  ########################################################
  # BUILD IMAGE AND DEPLOY ECS
  ########################################################

  docker-job:

    needs: download-artifact-job

    runs-on: ubuntu-latest


    permissions:
      contents: read
      actions: read
      id-token: write


    steps:


      ########################################################
      # Docker Setup
      ########################################################

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3


      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3



      ########################################################
      # AWS LOGIN
      ########################################################

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1



      ########################################################
      # LOGIN ECR
      ########################################################

      - name: Login Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2



      ########################################################
      # Download Docker Context
      ########################################################

      - name: Download Docker Context
        uses: actions/download-artifact@v4
        with:
          name: dockerBuildContext
          path: ./dockerBuildContext


      - name: Show Docker Context
        run: |
          ls -R dockerBuildContext



      ########################################################
      # BUILD AND PUSH IMAGE TO ECR
      ########################################################

      - name: Build and Push Docker Image
        id: build-image
        uses: docker/build-push-action@v6
        with:
          context: ./dockerBuildContext
          file: ./dockerBuildContext/Dockerfile
          push: true

          build-args: |
            JAR_FILE=${{ github.event.client_payload.artifact_name }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}

          tags: |
            968077439054.dkr.ecr.us-east-1.amazonaws.com/java-api:${{ github.sha }}


      ########################################################
      # UPDATE ECS TASK DEFINITION
      ########################################################

      - name: Render ECS task definition
        id: render-task-definition
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:

          task-definition: ecs/task-definition.json

          container-name: java-api

          image: 968077439054.dkr.ecr.us-east-1.amazonaws.com/java-api:${{ github.sha }}



      ########################################################
      # DEPLOY ECS SERVICE
      ########################################################

      - name: Deploy ECS service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2

        with:

          task-definition: ${{ steps.render-task-definition.outputs.task-definition }}

          service: java-api-service

          cluster: java-api-cluster-v1

          wait-for-service-stability: true